- name: NPM Publish
  # You may pin to the exact commit or the version.
  # uses: JS-DevTools/npm-publish@541aa6b21b4a1e9990c95a92c21adc16b35e9551
  uses: JS-DevTools/npm-publish@v2.1.0
  with:
    # The NPM access token to use when publishing
    token: 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
    # The NPM registry URL to use
    registry: # optional
    # The path to your package or its package.json file
    package: # optional
    # The distribution tag to publish
    tag: # optional
    # Determines whether the published package should be publicly visible, or restricted to members of your NPM organization.

    access: # optional
    # Attach provenance statements when publishing.
    provenance: # optional
    # Version check and release strategy. If "all" (default), package will be published if its version is simply not yet published. If "upgrade", package will be published if its version is higher than the existing tag, according to semantic versioning.

    strategy: # optional
    # Run npm with the --dry-run flag to avoid actually publishing anything.
    dry-run: # optional
